sudo: required
os: linux

cache:
  directories:
  - ~/.ccache
  - ~/.pkg-cache

services:
- docker

env:
  global:
    # GH_TOKEN
    - secure: "c1GqlOiglEeOBXAApC/u+wFYL6V1Da/oDU/RlxvLFpdA9PFPTTqBcuBiBCL5fVJEsl/u4yGlmjjHNqfxodqWhcbt6LP+jPhvARjb60MRiItEVn9jCINq3YaG0KD4/6+4ZSKY85KxW8b0+r41xfUQ5Y6+8EY3WxesXhlT9fZ7SSMEuZd9UJBWdjxkeD7fzs2BHpnDKoiL3mvCzT5cDvyjrFFJMofZkrTkx4iDeiOQYajU6D+caFlZH3pQOM/kPtpnxgiS7xXWdoD44eKnDEYC0Mmw+yZWtz4cd7VrTGrCuAlRNtmEPnNt+3LvY3tE5klorwU9STBhl1smRwxYElj4Oyq4TOq5m8E/m197H3C20y+ZYtvEJSgl2atz054/QfXMQF6OS2DQ0fmmVnA0KT30kyczsYI7g00pymJXpDZ2snn0wHELEAaKmHbHrEnFlkRqlS+WIDWlqv3x+KMih+Th2hx2jfCQcalh5qG+5QOxaBr6WzhFy2trSw/b5Q083rCOuIdFCI+e99TQ1nk66rkj9kLyOa0PHbr5i7mTFmhtlh9drfJE3HxsbJXILfmUZaOhGW7emHCwz79L3p6IEzksqX40T9QF9/vThybIobT6EH9dSgakKIb6T/Lbrkus4jgeQdtwN5ggP+eFE4si/5xPTzrYSUEg1NuhgHzd5jH+7EI="

archlinux:
  mount:
  - ~/.ccache:~/.ccache
  - ~/.pkg-cache:/var/cache/pacman/pkg
  packages:
  # Pacman packages
  - ccache
  - git

  before_install:
  # 1.Override `package-cleanup.hook` to preserve cache for travis.
  # 2.Enable ccache
  # 3.Multithreaded build and compress
  # 4.Suppress all gcc warnings
  - |
     sudo mkdir /etc/pacman.d/hooks/
     sudo ln -s /dev/null /etc/pacman.d/hooks/package-cleanup.hook
     sudo sed -i '/^BUILDENV/s/\!ccache/ccache/' /etc/makepkg.conf
     sudo sed -i '/#MAKEFLAGS=/c MAKEFLAGS="-j2"' /etc/makepkg.conf
     sudo sed -i '/^COMPRESSXZ/s/\xz/xz -T 2/' /etc/makepkg.conf
     sudo sed -i '$a   CFLAGS="$CFLAGS -w"'   /etc/makepkg.conf
     sudo sed -i '$a CXXFLAGS="$CXXFLAGS -w"' /etc/makepkg.conf
  script:
  - ./bin/build_packages.sh
  - ./bin/update_db.sh

script:
  - "curl -s https://raw.githubusercontent.com/bartoszek/arch-travis/master/arch-travis.sh | bash"
  - "echo pacman pkg cache size: $(du -h ~/.pkg-cache|cut -f1) in $(ls ~/.pkg-cache|wc -l) files"
  - ls -l pkgs/*/*.pkg.tar.zst

after_success:
  - ./bin/deploy.sh

