sudo: required
os: linux

cache:
  directories:
  - ~/.ccache
  - ~/.pkg-cache

services:
- docker

before_install:
  - sudo apt-get update
  - sudo apt-get -y install bash

script:
  - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
  - docker run --rm -v "$(pwd):/build" -v ~/.ccache:/home/travis/.ccache -v ~/.pkg-cache:/var/cache/pacman/pkg -e USERNAME="$USERNAME" -e EMAIL="$EMAIL" -e GH_TOKEN="$GH_TOKEN" --privileged archlinux:latest bash /build/ci/build_and_push_packages.sh

  - "echo pacman pkg cache size: $(du -h ~/.pkg-cache|cut -f1) in $(ls ~/.pkg-cache|wc -l) files"
  - ls -l pkgs/*/*.pkg.tar.zst

