sudo: required
os: linux

cache:
  directories:
  - ~/.ccache
  - ~/.pkg-cache

services:
- docker

env:
  global:
    - secure: "huJMSd/MeIcv+3wkhSTXQqGtX3hW4XoGN1BNIv/SuNGzrzFO6ex27xhN8G3tYW/t4g397wuEsgUfCtxCE3UXPKuRAr2sgXuxCglDqjJUhoUxlHqXSABttRjrLsxBPJXjGR3CZ3XTvbo9A49IyvhI1NXHZ5+1ygBRt6NU50fqjfabu/Ttj+fF2aC4HuH3TiXp32PhfMt4e8vzAHojlrAlVyAQWBJbEsl51l314asrSD/I1ozy5koECySckHPKte6xKqHo/vJenN34pOKL78wzQf/8C7yP/k+hfH48Ab7f2v1kYTQxWB6CmIyVAY9r+khlcTYnQrLPqZXPTp4q7PKI7oAQrb+snFytBvI/pVF0gs+uX8wuBTTQdCIVn96sjEkwnFyl1sSaGYvImIuL0okTg4v+v9fH5nk63LrFfU6cVRmBtFJyQkhbO3uAuRTXiGiuJVTyqR2HpFIM1BP9mqFniBd3UhXuIs4TkmktSOMIE+ycrvEJVx5Y8HQyvEAVWTBz2eUg2v84N9mhrdcdzvrlwaa9yNWY7DkrBACREDJa6iOTlISUhKKExF5CB8t9vySrFR4SDoDlXubPH7kHbgPrGLTJq5JRT1pPoOTwQqMNX0o4+K2Z2aHUHjNzT2n9HmaIMkT/SMnBi3Vg2YSza+qoqbaZkIJLeG7wnPuHkQP2sfY="


archlinux:
  mount:
  - ~/.ccache:~/.ccache
  - ~/.pkg-cache:/var/cache/pacman/pkg
  packages:
  # Pacman packages
  - ccache

  before_install:
  # 1.Override `package-cleanup.hook` to preserve cache for travis.
  # 2.Enable ccache
  # 3.Multithreaded build and compress
  # 4.Suppress all gcc warnings
  - |
     sudo mkdir /etc/pacman.d/hooks/
     sudo ln -s /dev/null /etc/pacman.d/hooks/package-cleanup.hook
     sudo sed -i '/^BUILDENV/s/\!ccache/ccache/' /etc/makepkg.conf
     sudo sed -i '/#MAKEFLAGS=/c MAKEFLAGS="-j2"' /etc/makepkg.conf
     sudo sed -i '/^COMPRESSXZ/s/\xz/xz -T 2/' /etc/makepkg.conf
     sudo sed -i '$a   CFLAGS="$CFLAGS -w"'   /etc/makepkg.conf
     sudo sed -i '$a CXXFLAGS="$CXXFLAGS -w"' /etc/makepkg.conf
  script:
  - ./bin/build_packages.sh
  - repo-add junest.db.tar.gz pkgs/*/*.pkg.tar.zst

before_install:
  - sudo apt-get update
  - sudo apt-get -y install awscli

script:
  - "curl -s https://raw.githubusercontent.com/bartoszek/arch-travis/master/arch-travis.sh | bash"
  - "echo pacman pkg cache size: $(du -h ~/.pkg-cache|cut -f1) in $(ls ~/.pkg-cache|wc -l) files"
  - ls -l pkgs/*/*.pkg.tar.zst

after_success:
  - ./bin/deploy.sh

